museum/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from museum import views

app_name = 'painting'

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.search, name='search'),
    path('church/all/', views.churches, name='church_all'),
    path('painter/all/', views.painters, name='painter_all'),
    path('engraving/all/', views.engravings, name='engraving_all'),
    path("paintings/tag/<slug:slug>/", views.tags_paintings, name="tag"),
    path('painting/<int:painting_id>/', views.detail_painting, name='detail'),
    path('church/<int:id_church>/', views.detail_church, name='church'),
    path('painter/<int:id_painter>/', views.detail_painter, name='painter'),
    path('engraving/<int:id_engraving>/', views.detail_engraving, name='engraving'),
    path('user/dashboard/painting/<int:painting_id>/', views.detail_painting_not_published, name='detail_not_published'),
    path('info/', views.info, name='info'),
]

urlpatterns += staticfiles_urlpatterns()

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('museum.urls')),
    path('user/', include('user.urls')),
    path('__debug__/', include('debug_toolbar.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('register/create/', views.register_create, name='register_create'),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout/', views.logout_user, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('edit/', views.edit_user, name='edit'),
    path('painting/create/', views.painting_create, name='painting_create'),
    path('painting/published/', views.painting_user_published, name='paintings_published'),
    path('author/create/', views.painting_author_create, name='painting_author_create'),
    path('church/create/', views.painting_church_create, name='painting_church_create'),
    path('engraving/all/', views.engravings, name= 'painting_engraving_all'),
    path('engraving/create/', views.engraving_create, name='painting_engraving_create'),
    path('engraving/create/data/', views.engraving_create_data, name='engraving_create_data'),
    path('painting/<int:id>/delete/', views.painting_delete, name='painting_delete'),
    path('painting/<int:id>/edit/', views.painting_edit, name='painting_edit'),
]

museum/models.py
from django.contrib.auth.models import User
from django.db import models

from tag.models import Tag


#pintura -> ManyToMany -> autor
class Author(models.Model):
    name = models.CharField(max_length=50)
    biography = models.TextField(blank=True)
    is_engraving = models.BooleanField(default=False)
    
    def __str__(self) -> str:
        return self.name
    
    class Meta:
        db_table = 'AUTHOR'
    

# igreja -> OneToMany -> pintura
# pintura -> ManyToOne -> igreja 
# Uma igreja pode possuir mais de uma pintura()
class Church(models.Model):
    name = models.CharField(max_length=50)
    city = models.CharField(max_length=50, blank=True)
    state = models.CharField(max_length=50, blank=True)

    def __str__(self) -> str:
        return self.name
    class Meta:
        db_table = 'CHURCH'
    

class Engraving(models.Model):
    name = models.CharField(max_length=50)
    book = models.CharField(max_length=50, blank=True)
    cover = models.ImageField(upload_to='engravings/cover/%Y/%m/%d/')
    
    author = models.ManyToManyField(
        Author, blank=True, default=None
    )

    def __str__(self) -> str:
        return self.name
    class Meta:
        db_table = 'ENGRAVING'
    


class Painting(models.Model):
    name = models.CharField(max_length=50)
    date = models.CharField(max_length=10, null=True, blank=True)
    description = models.TextField(blank=True)
    cover = models.ImageField(upload_to='museum/cover/%Y/%m/%d/')
    post_date = models.DateField(auto_now=True)
    summary = models.TextField(blank=True)
    is_published = models.BooleanField(default=False)

    author = models.ManyToManyField(
        Author, blank=True,
        default=None
    )

    church = models.ForeignKey(
        Church, on_delete=models.SET_NULL, null=True, blank=True,
        default=None
    )

    engraving = models.ManyToManyField(
        Engraving, blank=True,
        default=None
    )

    post_author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True
    )

    tag = models.ManyToManyField(Tag, blank=True, default=None)

    def __str__(self) -> str:
        return self.name

    class Meta:
        db_table = 'PAINTING'
    

museum/views.py
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator
from django.db.models import Count, Q
from django.http import Http404, HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.views.decorators.http import require_GET, require_POST

from tag.models import Tag
from utils.pagination import pagination

from .models import Author, Church, Engraving, Painting


@require_GET
def home(request: HttpRequest) -> HttpResponse:
    current_page = int(request.GET.get('page', 1))
    paintings = Painting.objects.filter(is_published=True).order_by('-id')
    paintings = paintings.select_related('church', 'post_author') \
                .defer('description', 'is_published')
    paintings = paintings.prefetch_related('engraving', 'author') \
                .defer('engraving__book', 'engraving__cover')

    page = pagination(paintings, current_page)
    return render(request, 'museum/pages/home.html', {
        'page':page,
        'obras':'-selected',
        'search_action': 'painting:search',
        'placeholder': 'Pesquise as obras pelo nome ou pelo resumo',
    })

@require_GET
def detail_painting(request: HttpRequest, painting_id: int) -> HttpResponse:
    try:
        painting = Painting.objects.select_related('church', 'post_author').prefetch_related('engraving__author', 'author').get(pk=painting_id, is_published=True)
        engravings = painting.engraving.all()
    except ObjectDoesNotExist:
        raise Http404('Objects not found in database')

    return render(request, 'museum/pages/detail_painting.html', {
        'painting': painting,
        'engravings':engravings,
        'range': [i+1 for i in range(engravings.count())],
        'isDetailPage': True,
        'searchbar': False,
        
    })

@require_GET
def tags_paintings(request, slug):
    current_page = int(request.GET.get('page', 1))  
    paintings = Painting.objects.filter(tag__slug=slug)
    tag_name = Tag.objects.get(slug=slug).name
    page = pagination(paintings, current_page)
    return render(request, 'museum/pages/tag_paintings.html', {
        'page':page,
        'tag_name': tag_name,
    })

@require_GET
def churches(request:HttpRequest) -> HttpResponse:
    churches_paintings = []
    churches = Church.objects.filter(painting__is_published = True).distinct().order_by('-id')
    churches = churches.annotate(
        num_paintings=Count('painting')
    )
    for church in churches:
        paintings_number = church.num_paintings
        if paintings_number > 0:
            churches_paintings.append((church, paintings_number))
    
    return render(request, 'museum/pages/search_church.html',{
            'churches': churches_paintings,
            'filterChurch': 'selected',
            'igrejas': '-selected',
            'search_action': 'painting:search',
            'placeholder': 'Pesquise as igrejas pelo nome, cidade ou estado',
        })


@require_GET
def detail_church(request: HttpRequest, id_church: int) -> HttpResponse:
    filter = request.GET.get('filter', '')
    current_page = int(request.GET.get('page', 1))
    paintings = Painting.objects.filter(church__id=id_church, is_published=True).order_by('-id')
    paintings = paintings.select_related('church', 'post_author')
    paintings = paintings.prefetch_related('engraving', 'author')

    
    if not paintings:
        raise Http404("there are no paintings related to this church id")
    church = paintings.first().church
    
    if filter == 'churches':
        search = request.GET.get('q', '')
        paintings = paintings.filter(Q(
            Q(name__icontains=search) | Q(summary__icontains=search)
        ))
    
    page = pagination(paintings, current_page)
    return render(request, 'museum/pages/church.html', {
        'page':page,
        'church': church,
        'filterChurch': 'selected',
        'placeholder': 'Pesquise pelas obras dessa igreja.',
        'limparPesquisa': True if filter == 'churches' else False,
        'search_result': search if filter == 'churches' else False,
        
    })

@require_GET
def painters(request: HttpRequest) -> HttpResponse:
    painter_paintings = []
    painters = Author.objects.filter(painting__is_published = True).distinct().order_by('-id')
    painters = painters.annotate(
        num_paintings = Count('painting')
    )
    for painter in painters:
        paintings_number = painter.num_paintings
        painter_paintings.append((painter, paintings_number))
    
    return render(request, 'museum/pages/search_painter.html',{
            'painters': painter_paintings,
            'filterPainter': 'selected',
            'pintores': '-selected',
            'search_action': 'painting:search',
            'placeholder': 'Pesquise os pintores pelo nome',
        })

@require_GET
def detail_painter(request: HttpRequest, id_painter: int)-> HttpResponse:
    filter = request.GET.get('filter', '')
    try:
        painter = Author.objects.get(pk=id_painter)
        paintings_this_painter = painter.painting_set.filter(is_published=True).order_by('-id')
        paintings_this_painter = paintings_this_painter.select_related('church', 'post_author').defer('church__city','church__state', 'description')
        paintings_this_painter = paintings_this_painter.prefetch_related('engraving', 'author').defer('engraving__book', 'author__biography')
        
    except ObjectDoesNotExist:
        raise Http404("Painter doesn't found in this database!")
    
    current_page = int(request.GET.get('page', 1))
    
    if filter == 'painters':
        search = request.GET.get('q', '')
        paintings_this_painter = paintings_this_painter.filter(Q(
            Q(name__icontains=search) | Q(summary__icontains=search)
        ))

    page = pagination(paintings_this_painter, current_page)
    return render(request, 'museum/pages/painter.html', {
        'painter': painter,
        'page': page,
        'filterPainter': 'selected',
        'placeholder': 'Pesquise pelas obras desse pintor.',
        'limparPesquisa': True if filter == 'painters' else False,
        'search_result': search if filter == 'painters' else False,

    })

@require_GET
def engravings(request: HttpRequest) -> HttpResponse:
    engraving_paintings = []
    engravings = Engraving.objects.filter(painting__is_published = True).distinct().order_by('-id')
    for engraving in engravings:
        paintings_number = engraving.painting_set.filter(is_published=True).count()
        engraving_paintings.append((engraving, paintings_number))
    
    return render(request, 'museum/pages/search_engraving.html',{
            'engravings': engraving_paintings,
            'filterEngraving': 'selected',
            'gravuras': '-selected',
            'search_action': 'painting:search',
            'placeholder': 'Pesquise a gravura pelo nome ou livro',
        })

@require_GET
def detail_engraving(request: HttpRequest, id_engraving:int) -> HttpResponse:
    try:
        engraving = Engraving.objects.get(pk=id_engraving)
        if not engraving.painting_set.filter(is_published=True).exists():
            raise Http404("Gravura não encontrada")
    except ObjectDoesNotExist:
        raise Http404("Gravura não encontrada")
    
    return render(request, 'museum/pages/detail_engraving.html', {
        'engraving': engraving,
        'search': False,
    })

@require_GET
def search(request: HttpRequest)-> HttpResponse:
    filter = request.GET.get("filter", "paintings")
    search = request.GET.get("q", "")
    current_page = int(request.GET.get('page', 1))
    
    if filter == 'paintings':
        template = 'museum/pages/search_painting.html'
        paintings = Painting.objects.filter(
            Q(
                Q(name__icontains=search) | Q(summary__icontains=search) 
            ) & Q(is_published=True)
        ).order_by('-id')
        paintings = paintings.select_related('church', 'post_author').prefetch_related('engraving', 'author')
        page = pagination(paintings, current_page)
        return render(request, template, {
            'page': page,
            'search_result': search,
            'is_search': True,
            'filter': filter,
            'obras': '-selected',
            'placeholder': 'Pesquise as obras pelo nome ou pelo resumo',
        })

    if filter == 'churches':
        template = 'museum/pages/search_church.html'
        churches_with_paintings_published = []
        churches = Church.objects.filter(
            Q(
                Q(name__icontains=search) | Q(city__icontains=search) | Q(state__icontains=search)
            ) 
        ).order_by('-id')
        

        for church in churches:
            painting_this_church = church.painting_set.filter(is_published=True).count()
            if painting_this_church > 0:
                churches_with_paintings_published.append((church, painting_this_church))

        return render(request, template,{
            'churches': churches_with_paintings_published,
            'search_result': search,
            'filterChurch': 'selected',
            'igrejas': '-selected',
            'placeholder': 'Pesquise as igrejas pelo nome, cidade ou estado',
        })
    
    if filter == "painters":
        template = 'museum/pages/search_painter.html'
        painters_with_paintings_published = []
        authors = Author.objects.filter(name__icontains=search).order_by('-id')

        for painter in authors:
            paintings_this_painter = painter.painting_set.filter(is_published=True).count()
            if paintings_this_painter > 0:
                painters_with_paintings_published.append((painter, paintings_this_painter))
    

        return render(request, template,{
            'painters': painters_with_paintings_published,
            'search_result': search,
            'filterPainter': 'selected',
            'pintores': '-selected',

museum/templates/museum/partials/engraving.html
<div class="center painting main-content-detail painting-list-item" id="card">
    <div class="painting-cover">
        <img src="{{ engraving.cover.url }}" alt="temporario" class="img-main no-filter">
    </div>
    <div class="painting-title-container">
        <h2 class="painting-title">{{ engraving.name | linebreaks }}</h2>
    </div>

    <div class="painting-author center-flex">
        <span class="painting-author-item">
            {% for author in engraving.author.all %}
                <i class="fas fa-paintbrush"></i>
                    <a href="{% url 'painting:painter' author.id %}">{{author}}</a>
                    <br>
            {%empty%}
                <i class="fas fa-paintbrush"></i>
                    Desconhecido
            {% endfor %}
        </span>
        <span class="painting-author-item">
            <i class="fas fa-calendar-alt"></i>
            {% if engranving.book %}
                {{ engranving.book }}
            {% else %}
                Desconhecido
            {% endif %}
        </span>
                
        
        <span class="painting-author-item">
            {% for painting in engraving.painting_set.all %}
                <i class="fas fa-brush"></i>
                    <a href="#">{{painting}}</a>
                    <br>
            {%empty%}
                <i class="fas fa-brush"></i>
                    Desconhecido
            {% endfor %}
        </span>

    </div>

    <div class="painting-meta-container">
        <div class="painting-meta painting-preparation">
            <h3 class="painting-meta-title"><i class="fas fa-user"></i> Autor do post</h3>
            <div class="painting-meta-text">
                {{painting.post_author.username}}
            </div>
        </div>
        <div class="painting-meta painting-servings">
            <h3 class="painting-meta-title"><i class="fas fa-calendar-alt"></i> Data do post</h3>
            <div class="painting-meta-text">
                {{painting.post_date}}
            </div>
        </div>
    </div>    

</div>

museum/templates/museum/partials/painting.html
<div class="center painting painting-list-item card">
  {% if isDetailPage is True %}
  <div class="painting-title-container">
    <h1 class="painting-title">{{ painting.name | linebreaks }}</h1>
  </div>
  {% endif %}
  <div class="painting-cover">
    {% if isDetailPage is not True %}
    <a class="no-filter" href="{% url 'painting:detail' painting.id %}">
      <img src="{{ painting.cover.url }}" alt="temporario" class="img-main" />
    </a>
    <div class="painting-title-container">
      <h2 class="painting-title">{{ painting.name | linebreaks }}</h2>
    </div>
    {% else %}
    <img
      src="{{ painting.cover.url }}"
      alt="temporario"
      class="img-main no-filter"
    />
    {% endif %}
  </div>

  <div class="painting-author center-flex">
    <span class="painting-author-item">
      {% for author in painting.author.all %}
      <i class="fas fa-paintbrush"></i>
      <a href="{% url 'painting:painter' author.id %}">{{author}}</a>
      <br />
      {%empty%}
      <i class="fas fa-paintbrush"></i>
      Desconhecido {% endfor %}
    </span>
    <span class="painting-author-item">
      <i class="fas fa-calendar-alt"></i>
      {% if painting.date %} {{ painting.date }} {% else %} Desconhecido {%endif%}
    </span>

    <span class="painting-author-item">
      <i class="fas fa-church"></i>
      {% if painting.church is not None %}
      <a href="{% url 'painting:church' painting.church.id %}">
        <span>{{ painting.church.name }}</span>
      </a>
      {% else %}
      <span>Igreja desconhecida</span>
      {% endif %}
    </span>
    <!--
        <span class="painting-author-item">
            {% for engraving in painting.engraving.all %}
                <i class="fas fa-brush"></i>
                    <a href="#">{{engraving.name}}</a>
                    <br>
            {%empty%}
                <i class="fas fa-brush"></i>
                    Desconhecido
            {% endfor %}
        </span>
        -->
  </div>
  {% if isDetailPage is not True %}
  <div class="painting-meta-container">
    <div class="painting-meta painting-preparation">
      <h3 class="painting-meta-title">
        <i class="fas fa-user"></i> Autor do post
      </h3>
      <div class="painting-meta-text">{{painting.post_author.username}}</div>
    </div>
    <div class="painting-meta painting-servings">
      <h3 class="painting-meta-title">
        <i class="fas fa-calendar-alt"></i> Data do post
      </h3>
      <div class="painting-meta-text">{{painting.post_date}}</div>
    </div>
  </div>
  {% endif %}
  <!-- <div class="painting-content justify">
    <div class="text-line">
      <div class="text-background">INTERTEXTO</div>
      <div class="inter-text-line"></div>
    </div>
    <p>{{ painting.summary }}</p>
  </div> -->

  {% if isDetailPage is not True %}
  <footer class="painting-footer">
    <a
      class="painting-read-more button button-dark button-full-width"
      href="{% url 'painting:detail' painting.id %}"
    >
      <i class="fas fa-eye"></i>
      <span>ver mais...</span>
    </a>
  </footer>
  {% endif %} {% if isDetailPage is True %}
  <!--
        <div class="painting-description justify">       
        {% if painting.tag.all %}
            <p>
                Tags:
                {% for tag in painting.tag.all %}
                    <a href="{% url 'painting:tag' tag.slug %}">
                        {{tag.name}},
                    </a>
                {% endfor %}
            </p>
        {% endif %}
        </div>
        -->
  {% if painting.engraving.all.count > 0 %} {% include
  'museum/partials/sliderShow.html' %} {% endif %}
  <div class="painting-meta-container">
    <div class="painting-meta painting-preparation">
      <h3 class="painting-meta-title">
        <i class="fas fa-user"></i> Autor do post
      </h3>
      <div class="painting-meta-text">{{painting.post_author.username}}</div>
    </div>
    <div class="painting-meta painting-servings">
      <h3 class="painting-meta-title">
        <i class="fas fa-calendar-alt"></i> Data do post
      </h3>
      <div class="painting-meta-text">{{painting.post_date}}</div>
    </div>
  </div>
  {% endif %}
</div>

museum/templates/museum/partials/painting_not_published.html
<div class="center painting painting-list-item card">
    <div class="painting-cover">
        <img src="{{ painting.cover.url }}" alt="temporario" class="img-main no-filter">
    </div>
    <div class="painting-title-container">
        <h2 class="painting-title">{{ painting.name | linebreaks }}</h2>
    </div>

    <div class="painting-author center-flex">
        <span class="painting-author-item">
            {% for author in painting.author.all %}
                <i class="fas fa-paintbrush"></i>
                    {{author}}
                    <br>
            {%empty%}
                <i class="fas fa-paintbrush"></i>
                    Desconhecido
            {% endfor %}
        </span>
        <span class="painting-author-item">
            <i class="fas fa-calendar-alt"></i>
            {% if painting.date %}
                {{ painting.date }}
            {% else %}
                Desconhecido
            {% endif %}
        </span>
                
        <span class="painting-author-item">   
            <i class="fas fa-church"></i>
                {% if painting.church is not None %}
                    <span>{{ painting.church.name }}</span>
                {% else %}
                    <span>Igreja desconhecida</span>
                {% endif %}
        </span>
        

    </div>

    <div class="painting-content justify">
        <p>{{ painting.summary }}</p>
    </div>

    <div class="painting-meta-container">
        <div class="painting-meta painting-preparation">
            <h3 class="painting-meta-title"><i class="fas fa-user"></i> Autor do post</h3>
            <div class="painting-meta-text">
                {{painting.post_author.username}}
            </div>
        </div>
        <div class="painting-meta painting-servings">
            <h3 class="painting-meta-title"><i class="fas fa-calendar-alt"></i> Data do post</h3>
            <div class="painting-meta-text">
                {{painting.post_date}}
            </div>
        </div>
    </div>
    
    {% if isDetailPage is True %}
        <div class="painting-description justify">
            {{ painting.description | linebreaks}}
        </div>
        
        {% if painting.engraving.all.count > 0 %}
            {% include 'museum/partials/sliderShow.html' %}
        {% endif %}
    {% endif %}

</div>

museum/templates/museum/partials/sliderShow.html
{% load static %}

<h2 style="text-align:center">Gravuras relacionadas a esta obra</h2>

<div class="slideshow-container">
    {% for engraving in engravings %}
        <div class="mySlides1">
            <a href=""><img src="{{engraving.cover.url}}" ></a>
            <div class="info-engraving">
                <h2> {{engraving.name}} </h2>
                {% for author in engraving.author.all %}
                <div class="author-engraving">
                    <i class="fas fa-paintbrush"></i>{{author.name}}
                </div>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
    <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
    <a class="next" onclick="plusSlides(1)">&#10095;</a>
    <br>
</div>
<div style="text-align:center">
    {% for i in range %}
        <span class="dot" onclick="currentSlide({{i}})"></span> 
    {% endfor %}
</div>