museum/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from museum import views

app_name = 'painting'

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.search, name='search'),
    path('church/all/', views.churches, name='church_all'),
    path('painter/all/', views.painters, name='painter_all'),
    path('engraving/all/', views.engravings, name='engraving_all'),
    path("paintings/tag/<slug:slug>/", views.tags_paintings, name="tag"),
    path('painting/<int:painting_id>/', views.detail_painting, name='detail'),
    path('church/<int:id_church>/', views.detail_church, name='church'),
    path('painter/<int:id_painter>/', views.detail_painter, name='painter'),
    path('engraving/<int:id_engraving>/', views.detail_engraving, name='engraving'),
    path('user/dashboard/painting/<int:painting_id>/', views.detail_painting_not_published, name='detail_not_published'),
    path('info/', views.info, name='info'),
]

urlpatterns += staticfiles_urlpatterns()

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('museum.urls')),
    path('user/', include('user.urls')),
    path('__debug__/', include('debug_toolbar.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('register/create/', views.register_create, name='register_create'),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout/', views.logout_user, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('edit/', views.edit_user, name='edit'),
    path('painting/create/', views.painting_create, name='painting_create'),
    path('painting/published/', views.painting_user_published, name='paintings_published'),
    path('author/create/', views.painting_author_create, name='painting_author_create'),
    path('church/create/', views.painting_church_create, name='painting_church_create'),
    path('engraving/all/', views.engravings, name= 'painting_engraving_all'),
    path('engraving/create/', views.engraving_create, name='painting_engraving_create'),
    path('engraving/create/data/', views.engraving_create_data, name='engraving_create_data'),
    path('painting/<int:id>/delete/', views.painting_delete, name='painting_delete'),
    path('painting/<int:id>/edit/', views.painting_edit, name='painting_edit'),
]

museum/models.py
from django.contrib.auth.models import User
from django.db import models

from tag.models import Tag


#pintura -> ManyToMany -> autor
class Author(models.Model):
    name = models.CharField(max_length=50)
    biography = models.TextField(blank=True)
    is_engraving = models.BooleanField(default=False)
    
    def __str__(self) -> str:
        return self.name
    
    class Meta:
        db_table = 'AUTHOR'
    

# igreja -> OneToMany -> pintura
# pintura -> ManyToOne -> igreja 
# Uma igreja pode possuir mais de uma pintura()
class Church(models.Model):
    name = models.CharField(max_length=50)
    city = models.CharField(max_length=50, blank=True)
    state = models.CharField(max_length=50, blank=True)

    def __str__(self) -> str:
        return self.name
    class Meta:
        db_table = 'CHURCH'
    

class Engraving(models.Model):
    name = models.CharField(max_length=50)
    book = models.CharField(max_length=50, blank=True)
    cover = models.ImageField(upload_to='engravings/cover/%Y/%m/%d/')
    
    author = models.ManyToManyField(
        Author, blank=True, default=None
    )

    def __str__(self) -> str:
        return self.name
    class Meta:
        db_table = 'ENGRAVING'
    


class Painting(models.Model):
    name = models.CharField(max_length=50)
    date = models.CharField(max_length=10, null=True, blank=True)
    description = models.TextField(blank=True)
    cover = models.ImageField(upload_to='museum/cover/%Y/%m/%d/')
    post_date = models.DateField(auto_now=True)
    summary = models.TextField(blank=True)
    is_published = models.BooleanField(default=False)

    author = models.ManyToManyField(
        Author, blank=True,
        default=None
    )

    church = models.ForeignKey(
        Church, on_delete=models.SET_NULL, null=True, blank=True,
        default=None
    )

    engraving = models.ManyToManyField(
        Engraving, blank=True,
        default=None
    )

    post_author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True
    )

    tag = models.ManyToManyField(Tag, blank=True, default=None)

    def __str__(self) -> str:
        return self.name

    class Meta:
        db_table = 'PAINTING'
    

museum/views.py
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator
from django.db.models import Count, Q
from django.http import Http404, HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.views.decorators.http import require_GET, require_POST

from tag.models import Tag
from utils.pagination import pagination

from .models import Author, Church, Engraving, Painting


@require_GET
def home(request: HttpRequest) -> HttpResponse:
    current_page = int(request.GET.get('page', 1))
    paintings = Painting.objects.filter(is_published=True).order_by('-id')
    paintings = paintings.select_related('church', 'post_author') \
                .defer('description', 'is_published')
    paintings = paintings.prefetch_related('engraving', 'author') \
                .defer('engraving__book', 'engraving__cover')

    page = pagination(paintings, current_page)
    return render(request, 'museum/pages/home.html', {
        'page':page,
        'obras':'-selected',
        'search_action': 'painting:search',
        'placeholder': 'Pesquise as obras pelo nome ou pelo resumo',
    })

@require_GET
def detail_painting(request: HttpRequest, painting_id: int) -> HttpResponse:
    try:
        painting = Painting.objects.select_related('church', 'post_author').prefetch_related('engraving__author', 'author').get(pk=painting_id, is_published=True)
        engravings = painting.engraving.all()
    except ObjectDoesNotExist:
        raise Http404('Objects not found in database')

    return render(request, 'museum/pages/detail_painting.html', {
        'painting': painting,
        'engravings':engravings,
        'range': [i+1 for i in range(engravings.count())],
        'isDetailPage': True,
        'searchbar': False,
        
    })

@require_GET
def tags_paintings(request, slug):
    current_page = int(request.GET.get('page', 1))  
    paintings = Painting.objects.filter(tag__slug=slug)
    tag_name = Tag.objects.get(slug=slug).name
    page = pagination(paintings, current_page)
    return render(request, 'museum/pages/tag_paintings.html', {
        'page':page,
        'tag_name': tag_name,
    })

@require_GET
def churches(request:HttpRequest) -> HttpResponse:
    churches_paintings = []
    churches = Church.objects.filter(painting__is_published = True).distinct().order_by('-id')
    churches = churches.annotate(
        num_paintings=Count('painting')
    )
    for church in churches:
        paintings_number = church.num_paintings
        if paintings_number > 0:
            churches_paintings.append((church, paintings_number))
    
    return render(request, 'museum/pages/search_church.html',{
            'churches': churches_paintings,
            'filterChurch': 'selected',
            'igrejas': '-selected',
            'search_action': 'painting:search',
            'placeholder': 'Pesquise as igrejas pelo nome, cidade ou estado',
        })


@require_GET
def detail_church(request: HttpRequest, id_church: int) -> HttpResponse:
    filter = request.GET.get('filter', '')
    current_page = int(request.GET.get('page', 1))
    paintings = Painting.objects.filter(church__id=id_church, is_published=True).order_by('-id')
    paintings = paintings.select_related('church', 'post_author')
    paintings = paintings.prefetch_related('engraving', 'author')

    
    if not paintings:
        raise Http404("there are no paintings related to this church id")
    church = paintings.first().church
    
    if filter == 'churches':
        search = request.GET.get('q', '')
        paintings = paintings.filter(Q(
            Q(name__icontains=search) | Q(summary__icontains=search)
        ))
    
    page = pagination(paintings, current_page)
    return render(request, 'museum/pages/church.html', {
        'page':page,
        'church': church,
        'filterChurch': 'selected',
        'placeholder': 'Pesquise pelas obras dessa igreja.',
        'limparPesquisa': True if filter == 'churches' else False,
        'search_result': search if filter == 'churches' else False,
        
    })

@require_GET
def painters(request: HttpRequest) -> HttpResponse:
    painter_paintings = []
    painters = Author.objects.filter(painting__is_published = True).distinct().order_by('-id')
    painters = painters.annotate(
        num_paintings = Count('painting')
    )
    for painter in painters:
        paintings_number = painter.num_paintings
        painter_paintings.append((painter, paintings_number))
    
    return render(request, 'museum/pages/search_painter.html',{
            'painters': painter_paintings,
            'filterPainter': 'selected',
            'pintores': '-selected',
            'search_action': 'painting:search',
            'placeholder': 'Pesquise os pintores pelo nome',
        })

@require_GET
def detail_painter(request: HttpRequest, id_painter: int)-> HttpResponse:
    filter = request.GET.get('filter', '')
    try:
        painter = Author.objects.get(pk=id_painter)
        paintings_this_painter = painter.painting_set.filter(is_published=True).order_by('-id')
        paintings_this_painter = paintings_this_painter.select_related('church', 'post_author').defer('church__city','church__state', 'description')
        paintings_this_painter = paintings_this_painter.prefetch_related('engraving', 'author').defer('engraving__book', 'author__biography')
        
    except ObjectDoesNotExist:
        raise Http404("Painter doesn't found in this database!")
    
    current_page = int(request.GET.get('page', 1))
    
    if filter == 'painters':
        search = request.GET.get('q', '')
        paintings_this_painter = paintings_this_painter.filter(Q(
            Q(name__icontains=search) | Q(summary__icontains=search)
        ))

    page = pagination(paintings_this_painter, current_page)
    return render(request, 'museum/pages/painter.html', {
        'painter': painter,
        'page': page,
        'filterPainter': 'selected',
        'placeholder': 'Pesquise pelas obras desse pintor.',
        'limparPesquisa': True if filter == 'painters' else False,
        'search_result': search if filter == 'painters' else False,

    })

@require_GET
def engravings(request: HttpRequest) -> HttpResponse:
    engraving_paintings = []
    engravings = Engraving.objects.filter(painting__is_published = True).distinct().order_by('-id')
    for engraving in engravings:
        paintings_number = engraving.painting_set.filter(is_published=True).count()
        engraving_paintings.append((engraving, paintings_number))
    
    return render(request, 'museum/pages/search_engraving.html',{
            'engravings': engraving_paintings,
            'filterEngraving': 'selected',
            'gravuras': '-selected',
            'search_action': 'painting:search',
            'placeholder': 'Pesquise a gravura pelo nome ou livro',
        })

@require_GET
def detail_engraving(request: HttpRequest, id_engraving:int) -> HttpResponse:
    try:
        engraving = Engraving.objects.get(pk=id_engraving)
        if not engraving.painting_set.filter(is_published=True).exists():
            raise Http404("Gravura não encontrada")
    except ObjectDoesNotExist:
        raise Http404("Gravura não encontrada")
    
    return render(request, 'museum/pages/detail_engraving.html', {
        'engraving': engraving,
        'search': False,
    })

@require_GET
def search(request: HttpRequest)-> HttpResponse:
    filter = request.GET.get("filter", "paintings")
    search = request.GET.get("q", "")
    current_page = int(request.GET.get('page', 1))
    
    if filter == 'paintings':
        template = 'museum/pages/search_painting.html'
        paintings = Painting.objects.filter(
            Q(
                Q(name__icontains=search) | Q(summary__icontains=search) 
            ) & Q(is_published=True)
        ).order_by('-id')
        paintings = paintings.select_related('church', 'post_author').prefetch_related('engraving', 'author')
        page = pagination(paintings, current_page)
        return render(request, template, {
            'page': page,
            'search_result': search,
            'is_search': True,
            'filter': filter,
            'obras': '-selected',
            'placeholder': 'Pesquise as obras pelo nome ou pelo resumo',
        })

    if filter == 'churches':
        template = 'museum/pages/search_church.html'
        churches_with_paintings_published = []
        churches = Church.objects.filter(
            Q(
                Q(name__icontains=search) | Q(city__icontains=search) | Q(state__icontains=search)
            ) 
        ).order_by('-id')
        

        for church in churches:
            painting_this_church = church.painting_set.filter(is_published=True).count()
            if painting_this_church > 0:
                churches_with_paintings_published.append((church, painting_this_church))

        return render(request, template,{
            'churches': churches_with_paintings_published,
            'search_result': search,
            'filterChurch': 'selected',
            'igrejas': '-selected',
            'placeholder': 'Pesquise as igrejas pelo nome, cidade ou estado',
        })
    
    if filter == "painters":
        template = 'museum/pages/search_painter.html'
        painters_with_paintings_published = []
        authors = Author.objects.filter(name__icontains=search).order_by('-id')

        for painter in authors:
            paintings_this_painter = painter.painting_set.filter(is_published=True).count()
            if paintings_this_painter > 0:
                painters_with_paintings_published.append((painter, paintings_this_painter))
    

        return render(request, template,{
            'painters': painters_with_paintings_published,
            'search_result': search,
            'filterPainter': 'selected',
            'pintores': '-selected',

museum/templates/museum/pages/church.html
{% extends 'templates/pages/global.html' %}
{% block title %}{{church.name}} | {% endblock title %}
{% block content %}

<div class="text-secondary-page">
    <div class="center-flex" id="church-name">
        <i class="fa-solid fa-church fa-lg logo-info"></i>
        <h1>{{ church.name }}</h1>
    </div>
    
    <div class="center-flex" id="church-location">
        {% if church.city %}
        <i class="fa-solid fa-flag logo-info"></i>
        <h3>{{ church.city }}</h3>
        {% endif %}
        {% if church.state %}   
             <h3>, {{ church.state }}</h3>
        {% endif %}
    </div>
    {% if limparPesquisa is True %}
        <h2>Pesquisa realizada: {{search_result}}</h2>
        <h2><a href="{% url 'painting:church' church.id %}">Limpar Busca</a></h2>
    {% endif %}  
</div>
    {% if page.total_paintings == 1 %}
        <h2 class="gray-text">Pintura dessa igreja</h2>
        <br>
        <div class="main-content  container" id="one-item">
            {% for painting in page.paintings %} 
                
                    {% include 'museum/partials/painting.html' %}
                
            {% endfor %}
        </div>
    {% else %}
        <h2 class="gray-text">Lista das pinturas dessa igreja</h2>
        <br>
        <div class="main-content main-content-list container" id="church-page">
            {% for painting in page.paintings %}
                {% include 'museum/partials/painting.html' %}
            {% endfor %}
        </div>
        <div class="container">
            {% include 'templates/partials/pagination.html' %}
        </div>
    {% endif %}

    

{% endblock content %}

museum/templates/museum/pages/detail_engraving.html
{% extends 'templates/pages/global.html' %}
{% block title %}{{engraving.name}} | {% endblock title %}
{% block content %}

<div class="text-secondary-page">
    <div class="center-flex" id="church-name">
        <h1>Nome: {{ engraving.name }}</h1>
    </div>
    
    <div class="center-flex" id="church-location">
        
        <h3>Livro: {{ engraving.book }}</h3>
    </div>    

</div>
        <div class="main-content  container" id="one-item">
            {% if engraving %}
                {% include 'museum/partials/engraving.html' %}
            {% endif %}

        </div>

{% endblock content %}

museum/templates/museum/pages/detail_painting.html
{% extends 'templates/pages/global.html' %}
{% block title %}{{painting.name}} | {% endblock title %}
{% block content %}

<div class="main-content main-content-detail container" id="details-page">
    {% if edit is True %}
        <div class="login-message">
            <h2><a href="{% url 'user:dashboard' %}">Dashboard</a></h2>
        </div>
    {% endif %}
    {% include 'museum/partials/painting.html' %}
</div>
    {% if edit is True %}
        <div class="form-content center form-content-grid">
            <div class="form-group ">
                <a class="link-to-button" href="{% url 'user:painting_edit' painting.id %}">Editar</a>
            </div>
            <form class = "form-delete" action="{% url 'user:painting_delete' painting.id %}" method="POST">
                {% csrf_token %}
                <button class="plaintext-button" type="submit">Excluir</button>
            </form>
        </div>
    {% endif %}

{% endblock content %}

museum/templates/museum/pages/detail_painting_edit.html
{% extends 'templates/pages/global.html' %}
{% block title %}{{painting.name}} | {% endblock title %}
{% block content %}

<div class="main-content main-content-detail container" id="details-page">
    {% if edit is True %}
        <div class="login-message">
            <h2><a href="{% url 'user:dashboard' %}">Dashboard</a></h2>
        </div>
    {% endif %}
    {% include 'museum/partials/painting_not_published.html' %}
</div>
    {% if edit is True %}
        <div class="form-content center form-content-grid">
            <div class="form-group ">
                <a class="link-to-button" href="{% url 'user:painting_edit' painting.id %}">Editar</a>
            </div>
            <form class = "form-delete" action="{% url 'user:painting_delete' painting.id %}" method="POST">
                {% csrf_token %}
                <button class="plaintext-button" type="submit">Excluir</button>
            </form>
        </div>
    {% endif %}

{% endblock content %}

museum/templates/museum/pages/home.html
{% extends 'templates/pages/global.html' %}
{% block title %}Home | {% endblock title %}
{% block content %}
    {% include 'templates/partials/messages.html' %}
    <div class="main-content main-content-list container">
        {% for painting in page.paintings %}          
            {% include 'museum/partials/painting.html' %} 
        {%empty%}  
        <h1>No paintings found here!</h1>
        {% endfor %}
    </div>
    <div class="container">
        {% include 'templates/partials/pagination.html' %}
    </div>
    
{% endblock content %}

museum/templates/museum/pages/info.html
{% extends 'templates/pages/global.html' %}
{% block title %} info | {% endblock title %}
{% block content %}

{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div id="info-page">
        <img id='unb-logo' src= "{% static '/static/images/unb-logo.png' %}" alt="UnB logo" />
    
        <div class="gray-box flex-center justify info-text", id="info-message">
            <p> Bem vindos! O presente site é um dos resultados direto do projeto de pesquisa
                 “Um Barroco narrativo: uma análise iconológica da hagiografia de Santa Teresa dÁvila
                  nos painéis da Igreja da Ordem Terceira do Carmo do Recife, Capitania de Pernambuco”
                   realizado entre os anos 2016 e 2018 por meio do Programa de Iniciação Científica
                    da  Universidade de Brasília (UnB) sob orientação do professor André Cabral Honor
                     (DHIS/PPGHIS/UnB).
            </p>
    
        </div>
    
        <div class="gray-box flex-center justify info-text", id="info-thanks">
        <p>
            Agradecimento especial aos meus grandes amigos Yan e Guilherme,
            que são responsáveis pela criação e manutenção do site.
        </p>
        </div>
    </div>

    
</body>
</html>

{% endblock content %}

museum/templates/museum/pages/painter.html
{% extends 'templates/pages/global.html' %}
{% block title %}{{painter.name}} | {% endblock title %}
{% block content %}
<div class="text-secondary-page">
    
    <div class="center-flex">
        <i class="fa-solid fa-paintbrush fa-lg logo-info"></i>
        <h1 id="painter-name">{{ painter.name }}</h1>
        <i class="fa-solid fa-paintbrush fa-lg logo-info"></i>
    </div>
    {% if limparPesquisa is True %}
        <h2>Pesquisa realizada: {{search_result}}</h2>
        <h2><a href="{% url 'painting:painter' painter.id %}">Limpar Busca</a></h2>
    {% endif %}
    
    {% if page.total_paintings == 1 %}
        <h2 class="gray-text">Obra deste pintor:</h2>
        <br>
        <div class="main-content  container" id="one-item">
            {% for painting in page.paintings %} 
                {% include 'museum/partials/painting.html' %}    
            {% endfor %}
        </div>
    {% else %}
        <h2 class="gray-text">Obras deste pintor:</h2>
        <br>
        <div class="main-content main-content-list container">
            {% for painting in page.paintings %}            
                {% include 'museum/partials/painting.html' %}
            {% endfor %}
        </div>
        <div class="container">
            {% include 'templates/partials/pagination.html' %}
        </div>
    {% endif %}   
</div>
{% endblock content %}

museum/templates/museum/pages/search_church.html
{% extends 'templates/pages/global.html' %}
{% block title %}Home | {% endblock title %}
{% block content %}

<div class="main-content center container">
    <!-- <h2>Igrejas encontradas pela busca: {{search_result}}</h2> -->
    {% if churches %}
    <div class="search-page"> 
        
        <table class="table">
            <thead>
                <tr>
                <th scope="col">Igreja</th>
                <th scope="col">Cidade</th>
                <th scope="col">Estado</th>
                <th scope="col">Obras</th>
                </tr>
            </thead>
            <tbody>
                {% for church, qtd_paintings in churches %}
                    <tr>
                        <td class="main-table-name"><a class="table-link" href="{% url 'painting:church' church.id %}">{{church.name}}</a></td>
                        <td>
                            {% if church.city %}
                                {{church.city}}
                            {% else %}
                                ---
                            {% endif %}
                        </td>                      
                        <td>
                            {% if church.state %}
                                {{church.state}}
                            {% else %}
                                ---
                            {% endif %}
                        </td>
                        <td>
                            {{qtd_paintings}}
                        </td>

                    </tr>
                    {% endfor %}
            </tbody>
        </table>
    </div>
        {% else %}
            <h1>Nenhuma igreja encontrada com essa busca</h1>
        {% endif %}
</div>
    
{% endblock content %}

museum/templates/museum/pages/search_engraving.html
{% extends 'templates/pages/global.html' %}
{% block title %}Home | {% endblock title %}
{% block content %}

<div class="main-content center container">
    <!-- <h2>Gravuras encontradas pela busca: {{search_result}}</h2> -->
    {% if engravings %}
    <div class="search-page"> 
        
        <table class="table">
            <thead>
                <tr>
                <th scope="col">Gravura</th>
                <th scope="col">Livro</th> 
                <th scope="col">Obras</th>
                </tr>
            </thead>
            <tbody>
                {% for engraving, qtd_paintings in engravings %}
                    <tr>
                        <td class="main-table-name"><a class="table-link" href="{% url 'painting:engraving' engraving.id %}">{{engraving.name}}</a></td>
                                              
                        <td>
                            {% if engraving.book %}
                                {{engraving.book}}
                            {% else %}
                                ---
                            {% endif %}
                        </td>
                        <td>
                            {{qtd_paintings}}
                        </td>

                    </tr>
                    {% endfor %}
            </tbody>
        </table>
    </div>
        {% else %}
            <h1>Nenhuma gravura encontrada com essa busca</h1>
        {% endif %}
</div>
    
{% endblock content %}

museum/templates/museum/pages/search_painter.html
{% extends 'templates/pages/global.html' %}
{% block title %}Home | {% endblock title %}
{% block content %}

<div class="main-content center container">
    <!-- <h2>Pintores encontrados pela busca: {{search_result}}</h2> -->
        {% if painters %}
        <div class= "search-page">
            <table class="table">
                <thead>
                    <tr>
                    <th scope="col">Pintor</th>
                    <th scope="col">Obras</th>
                    </tr>
                </thead>
                <tbody>
                    {% for painter, qtd_paintings in painters %}
                        <tr>
                            <td class="main-table-name"><a class="table-link" href="{% url 'painting:painter' painter.id %}">{{painter.name}}</a></td>
                            <td>{{qtd_paintings}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
            <h1>Nenhum pintor encontrado com essa busca</h1>
        {% endif %}
</div>
    
{% endblock content %}

museum/templates/museum/pages/search_painting.html
{% extends 'templates/pages/global.html' %}
{% block title %}Home | {% endblock title %}
{% block content %}

<!-- <h2>Pinturas encontradas pela busca: {{search_result}}</h2> -->

{% if page.total_paintings > 0 %}
    {% if page.total_paintings == 1 %}
        <div class="main-content  container" id="one-item">
            {% for painting in page.paintings %}           
                    {% include 'museum/partials/painting.html' %}        
            {% endfor %}
        </div>
    
    {% else %}
        <div class="main-content main-content-list container">
            {% for painting in page.paintings %} 
                {% include 'museum/partials/painting.html' %}
            {% endfor %}
        </div>
        <div class="container">
            {% include 'templates/partials/pagination.html' %}
        </div>
    {% endif %}
{% else %}
    <h1 class="main-content  container" id="one-item" >Nenhuma pintura encontrada pela busca!</h1>
{% endif %}
{% endblock content %}

museum/templates/museum/pages/tag_paintings.html
{% extends 'templates/pages/global.html' %}
{% block title %}{{tag_name}} | {% endblock title %}
{% block content %}
    {% include 'templates/partials/messages.html' %}
    <div class="main-content main-content-list container">
        {% for painting in page.paintings %}          
            {% include 'museum/partials/painting.html' %} 
        {%empty%}  
        <h1>No paintings found here!</h1>
        {% endfor %}
    </div>
    <div class="container">
        {% include 'templates/partials/pagination.html' %}
    </div>
    
{% endblock content %}