museum/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from museum import views

app_name = 'painting'

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.search, name='search'),
    path('church/all/', views.churches, name='church_all'),
    path('painter/all/', views.painters, name='painter_all'),
    path('engraving/all/', views.engravings, name='engraving_all'),
    path("paintings/tag/<slug:slug>/", views.tags_paintings, name="tag"),
    path('painting/<int:painting_id>/', views.detail_painting, name='detail'),
    path('church/<int:id_church>/', views.detail_church, name='church'),
    path('painter/<int:id_painter>/', views.detail_painter, name='painter'),
    path('engraving/<int:id_engraving>/', views.detail_engraving, name='engraving'),
    path('user/dashboard/painting/<int:painting_id>/', views.detail_painting_not_published, name='detail_not_published'),
    path('info/', views.info, name='info'),
]

urlpatterns += staticfiles_urlpatterns()

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('museum.urls')),
    path('user/', include('user.urls')),
    path('__debug__/', include('debug_toolbar.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('register/create/', views.register_create, name='register_create'),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout/', views.logout_user, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('edit/', views.edit_user, name='edit'),
    path('painting/create/', views.painting_create, name='painting_create'),
    path('painting/published/', views.painting_user_published, name='paintings_published'),
    path('author/create/', views.painting_author_create, name='painting_author_create'),
    path('church/create/', views.painting_church_create, name='painting_church_create'),
    path('engraving/all/', views.engravings, name= 'painting_engraving_all'),
    path('engraving/create/', views.engraving_create, name='painting_engraving_create'),
    path('engraving/create/data/', views.engraving_create_data, name='engraving_create_data'),
    path('painting/<int:id>/delete/', views.painting_delete, name='painting_delete'),
    path('painting/<int:id>/edit/', views.painting_edit, name='painting_edit'),
]

user/models.py
from django.db import models

# Create your models here.

user/forms/edit_user.py
from django import forms
from django.core.exceptions import ValidationError
from utils.django_form import email_validate, strong_password


class ChangePasswordForm(forms.Form):
    
    first_name = forms.CharField(
        error_messages={'required': 'Escreva seu nome'},
        label='Edite seu nome',
        min_length=3, max_length=20,
    )
    last_name = forms.CharField(
        error_messages={'required': 'Escreva seu sobrenome'},
        label='Edite seu sobrenome',
        min_length=2, max_length=100, 
    )

    password = forms.CharField(
        widget=forms.PasswordInput(),
        label='Senha nova',
        help_text = ('A senha deve ter pelo menos uma letra, um número e ter no mínimo 8 caracteres.'),
        validators = [strong_password]
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(),
        label='Confirme a nova senha'
    )

    def clean(self):
        
        cleaned_data = super().clean()

        password = cleaned_data.get('password')
        password2 = cleaned_data.get('password2')

        if password != password2:
            password_confirmation_error = ValidationError(
                'As senhas estão diferentes, por favor digite-as novamente',
                code='invalid'
            )
            raise ValidationError({
                'password': password_confirmation_error,
                'password2': password_confirmation_error
            })

        return cleaned_data

user/forms/login.py
from django import forms


#Neste caso não iremos utilizar um formulário atrelado a um model, ou seja, um Model.Form
#nos iremos utilizar um Form.
class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={
            'placeholder': 'Seu usuário'
        }),
        label='Usuário'
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'placeholder': 'Sua senha'
        }),
        label='Senha'
    )

user/views.py
import json
from http.client import HTTPResponse

from django.contrib import messages
from django.contrib.auth import (authenticate, login, logout,
                                 update_session_auth_hash)
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404, HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.decorators.http import (require_GET, require_http_methods,
                                          require_POST)
from pyUFbr.baseuf import ufbr

from museum.models import Author, Engraving, Painting
from utils.pagination import pagination

from .forms import (ChangePasswordForm, LoginForm, RegisterAuthorForm,
                    RegisterChurchForm, RegisterEngravingForm, RegisterForm,
                    RegisterPaintingForm)


#UTILIZAR A SESSÃO DO USUÁRIO PARA PODER TRAFEGAR DADOS DE UMA VIEW PARA OUTRA
#UMA VEZ QUE SÃO VIEWS DIFERENTES. CADA UMA COM SUA RESPONSABILIDADE
@require_GET
def register(request: HttpRequest)-> HttpResponse:
    if request.user.is_authenticated:
        return redirect('user:dashboard')

    register_form = request.session.get('register_form_data', None)
    
    form = RegisterForm(register_form)

    return render(request, 'user/pages/register.html', {
        'form': form,
        'form_action': 'user:register_create',
        'search': False,
    })

#ESSA VIEW É APENAS PARA TRATAR OS DADOS NÃO IRÁ RENDERIZAR
#DEPENDENDO ELE CRIA O USUÁRIO OU RETORNA PARA REGISTER MOSTRANDO OS ERROS
@require_POST
def register_create(request: HttpRequest)-> HttpResponse:
    
    POST = request.POST
    request.session['register_form_data'] = POST
    form = RegisterForm(POST)
    
    if form.is_valid():
        user = form.save(commit=False)
        user.set_password(user.password)
        user.save()
        messages.success(request, "Usuário criado, por favor faça o log in.")

        del(request.session['register_form_data'])
        return redirect('user:login')

    return redirect('user:register')

@require_GET
def login_view(request:HttpRequest)-> HttpResponse:
    if request.user.is_authenticated:
        return redirect('user:dashboard')

    login_form = LoginForm()
    
    return render(request, 'user/pages/login.html',{
        'form': login_form,
        'form_action': 'user:login_create',
        'search': False,
    })

@require_POST
def login_create(request: HttpRequest)-> HttpResponse:
    
    login_form = LoginForm(request.POST)
    if login_form.is_valid():
        username = login_form.cleaned_data.get('username', '')
        password = login_form.cleaned_data.get('password', '')
        authenticated_user = authenticate(request,
            username = username,
            password = password
        )
        if authenticated_user is not None:
            messages.success(request, f'Usuário {username} logado com sucesso!')
            login(request, authenticated_user)
            return redirect('user:dashboard')
        
        messages.error(request, 'Login inválido! Por favor, tente novamente.')
        return redirect('user:login')
    
    messages.error(request, 'Error ao validar o formulário.')
    return redirect('user:login')

#Utilizamos uma proteção para o nosso logout para ele não aceitar requisição GET
#com isso para deslogar tem que ser necessariamente pelo site
@require_POST
@login_required(login_url='user:login', redirect_field_name='next')
def logout_user(request: HttpRequest)-> HttpResponse:
    
    if request.POST.get('username') != request.user.username:
        messages.error(request, 'Error ao realizar logout')
        return redirect('painting:home')
    
    logout(request)
    messages.success(request, 'Usuário deslogado com sucesso')
    return redirect('user:login')

@login_required(login_url='user:login')
def edit_user(request):
    user = request.user
    if request.method == 'POST':
        form = ChangePasswordForm(data=request.POST or None)
        
        if form.is_valid():
            user.first_name = form.cleaned_data.get('first_name', '')
            user.last_name = form.cleaned_data.get('last_name', '')
            user.set_password(form.cleaned_data.get('password'))
            user.save()
            update_session_auth_hash(request, user)
            messages.success(request, "Usuário alterado com sucesso!")

    else:
        form = ChangePasswordForm(data=request.POST or None, initial={
            'first_name': user.first_name,
            'last_name': user.last_name,
        })

    return render(request, 'user/pages/edit_user.html', {
        'form_action': 'user:edit',
        'search': False,
        'form': form,
    })
    

@require_GET
@login_required(login_url='user:login')
def dashboard(request:HttpRequest) -> HttpResponse:
    user = request.user
    engraving = request.session.get('is_engraving', '')
    
    if engraving:
        del(request.session['is_engraving']) 

    paintings = Painting.objects.filter(
        is_published=False, post_author=user
    ).order_by('-id')


    return render(request, 'user/pages/dashboard.html', {
        'paintings': paintings,
        'search': False,
    })

@require_http_methods(['GET', 'POST'])
@login_required(login_url='user:login')
def painting_edit(request:HttpRequest, id:int)-> HttpResponse:
    request.session['painting_edit_id'] = id
    engravings_id = request.session.get('engravings', None)
    is_engraving = request.session.get('is_engraving', '')
    
    if is_engraving:
        del(request.session['is_engraving'])

    try:
        user = request.user
        painting = Painting.objects.prefetch_related('author', 'engraving').get(
            pk=id,
            is_published=False, 
            post_author=user,
        )
        authors = Author.objects.filter(is_engraving=False)
 
    except ObjectDoesNotExist:
        raise Http404("Painter doesn't found in this database!")
    
    if engravings_id is None:
        engravings = painting.engraving.all() 
        
    if engravings_id != None:
        engravings = __load_engraving(engravings_id)


    form = RegisterPaintingForm(
            data=request.POST or None,
            files=request.FILES or None,
            instance=painting
        )

    authors_registered = painting.author.all()
    
    if form.is_valid():
        authors = [Author.objects.get(pk=int(id)) for id in request.POST.getlist('pintores_selecionados')]
        pant = form.save(commit=False)
        pant.author.set(authors)
        pant.engraving.set(engravings)
        pant.post_author = user
        pant.is_published = False
        pant.save()

        del(request.session['painting_edit_id'])
        if request.session.get('engravings'):
            del(request.session['engravings'])
        
        messages.success(request, 'Pintura alterada com sucesso!')
        return redirect(reverse('user:painting_edit', args=(id,)))


    return render(request, 'user/pages/dashboard_painting.html', {
        'method': 'Editar',
        'form': form,
        'search': False,
        'engravings': engravings,
        'authors': authors,
        'authors_registered': authors_registered,
    })

@require_http_methods(['GET', 'POST'])
@login_required(login_url='user:login')
def painting_create(request:HttpRequest)-> HttpResponse:
    session_id = request.session.get('painting_edit_id', '')
    engravings_id = request.session.get('engravings', [])
    is_engraving = request.session.get('is_engraving', '')

    if session_id:
        del(request.session['painting_edit_id'])
    if is_engraving:
        del(request.session['is_engraving'])
      
    engravings = __load_engraving(engravings_id) 

    user = request.user
    form = RegisterPaintingForm(
            data=request.POST or None,
            files=request.FILES or None,
    )    
    if form.is_valid():
        authors = [Author.objects.get(pk=int(id)) for id in request.POST.getlist('pintores_selecionados')]
        pant = form.save(commit=False)
        pant.post_author = user
        pant.is_published = False
        pant.save()
        
        for author in authors:
            pant.author.add(author)
        for engraving in engravings:
            pant.engraving.add(engraving)
        
        messages.success(request, 'Pintura cadastrada com sucesso!')
        if request.session.get('engravings'):
            del(request.session['engravings'])
        return redirect('user:dashboard')
    
    authors = Author.objects.filter(is_engraving=False).order_by('name')

    return render(request, 'user/pages/dashboard_painting.html', {
        'method': 'Criar',
        'form': form,
        'authors': authors,
        'search': False,
        'engravings': engravings,
    })


@require_http_methods(['GET', 'POST'])
@login_required(login_url='user:login')
def painting_author_create(request:HttpRequest) -> HTTPResponse:
    id = request.session.get('painting_edit_id', '')
    engraving = request.session.get('is_engraving', '')

    form = RegisterAuthorForm(data=request.POST or None)
    
    if form.is_valid():
        author = form.save(commit=False)
        if engraving:
            author.is_engraving = True
            
        author.save()
        messages.success(request, "Autor cadastrado com sucesso")
        #TENTAR ARMAZENAR NO SESSION OS DADOS QUE ESTAVAM NO FORMULÁRIO ANTES DE CRIAR O AUTOR
        if engraving:
            del(request.session['is_engraving'])
            return redirect('user:painting_engraving_create')

        if id:
            return redirect(reverse('user:painting_edit', args=(id,)))
        
        return redirect('user:painting_create')

    return render(request, 'user/pages/dashboard_author.html', {
        'form': form,
        'search': False,
    })


@require_POST
@login_required(login_url='user:login')

user/templates/user/pages/all_engravings.html
{% extends 'templates/pages/global.html' %}
{% block title %}Gravuras | {% endblock title %}
{% block content %}

<div class="main-content center container">
    <div class="search-container">
        <div class="container">

            <form action="" class="search-form">
                <input type="text" id="search_engraving" onkeyup="searchElementTable()" 
            placeholder="Procure pela gravura..." class="search-input">
            <i class="fas fa-search search-button"></i>
            </form>
             
            <h3 id="text-engraving">Não encontrou a gravura na lista? <a href="{% url 'user:painting_engraving_create' %}">Adicione</a></h3>
        </div>
    </div>
    <h2>Todas as gravuras cadastradas: {{search_result}}</h2>
    {% if engravings %}
    <form action="{% url 'user:engraving_create_data' %}" method="POST">
        {% csrf_token %}
        <div class="search-page">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Selecionar</th>
                        <th scope="col">Gravura</th>
                        <th scope="col">Livro</th>
                        <th scope="col">Obras</th>
                    </tr>
                </thead>
            
                <tbody class="table-body-wrapper">
                    {% for engraving, qtd_paintings in engravings %}
                    <tr id='linha_tabela'>

                        <td><input type="checkbox" id="engraving_{{engraving.id}}" name="engraving"
                                value="{{engraving.id}}"></td>
                                
                        <td class="main-table-name test-main">
                            <a href=""> {{engraving.name}} </a>  
                            <i class="fa-solid fa-eye"></i>
                            <div class="image-container"> 
                                <img class="image-hover" src="{{engraving.cover.url}}" alt="">
                             </div>
                            
                        </td>         

                        <td>
                            {% if engraving.book %}
                            {{engraving.book}}
                            {% else %}
                            ---
                            {% endif %}
                        </td>
                        <td>
                            {{qtd_paintings}}
                        </td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="form-content">
            <button style="margin-top:5%" class="plaintext-button" type="submit">Enviar</button>
        </div>

    </form>
    {% else %}
    <h1>Nenhuma gravura encontrada com essa busca</h1>
    {% endif %}
</div>

{% endblock content %}

user/templates/user/pages/dashboard.html
{% extends 'templates/pages/global.html' %}

{% load static %}

{% block title %}Dashboard | {% endblock title %}
{% block content %}
{% include 'templates/partials/messages.html' %}
    <div class="main-content center container dashboard-card">

        <div class="dashboard-header">

            <div class="avatar center-flex">
                    <a class="avatar-photo-container open-button" onclick="openForm()">
                        <img class="avatar-photo" src= "{% static '/static/images/unb-logo.png' %}" alt="UnB logo" />
                        <i class="fa-lg fa-solid fa-pencil avatar-icon"></i>
                        
                    </a>
                    <!-- The form -->
                    <div class="form-popup" id="myForm">
                        <form class="form-container">
                        <h4>Trocar avatar</h4>
                    
                        <button type="button" class="btn cancel plaintext-button" onclick="closeForm()">Fechar</button>
                        </form>
                    </div>
                
            </div>

            <div class="dashboard-info">
                <div class="user-info center-flex-main">
                    <h4>Nome </h4> 
                    <p> {{user.get_full_name}}</p>  
                </div>

                <div class="user-info center-flex-main">
                    
                    <h4>E-mail </h4>
                    <p> {{user.email}} </p>
                </div>

                <div class="user-info center-flex-main">
                    <h4> Usuário </h4> 
                    <p> {{user.username}}</p>
                </div>
            </div>

            
            
            <a class="dashboard-button-dark center-flex-main" href="{% url 'user:edit' %}">Editar</a>
        </div>
        
        <div class="dashboard-content">

            <div class='login-message'>
                <h2 class="dash-message">Bem vindo ao seu dashboard {% if user.first_name %}{{ user.first_name }}{% else %}{{user.username}}{% endif %}!</h2>
                <h4>Ver todas as suas pinturas publicadas. <a href="{% url 'user:paintings_published' %}">Clique aqui.</a></h4>
            </div>
    
    
            <div class="authors-dashboard-container">
                <div class='login-message center' id="dashboard-button-container">
                    <a class="dashboard-button" onclick="sessionStorage.clear()" href="{% url 'user:painting_create' %}"> 
                        <span> Criar nova pintura </span>
                    </a>
                </div>
                <h3>Suas pinturas que não foram publicadas:</h3>
                <ul>
                    {% for painting in paintings %}
                        <div class="painting-list-not-published">
                            <li>
                                <div class="painting-modification">
                                    <a href="{% url 'painting:detail_not_published' painting.id %}">{{painting.name}}</a>
                                    <div class="painting-edit">
                                        <i class="fas fa-pen"></i>
                                        <a href="{% url 'user:painting_edit' painting.id %}">Editar</a>
                                        <form class = "form-delete" action="{% url 'user:painting_delete' painting.id %}" method="POST">
                                            {% csrf_token %}
                                            <i class="fas fa-trash"></i>
                                            <button id = "button-delete" class="plaintext-button" type="submit">Excluir</button>
                                        </form>
                                    </div>
                                </div>
                            </li>
                        </div>
                    {%empty%}
                        <h3>Nenhuma pintura cadastrada. Crie o seu post.</h3>
                    {% endfor %}
                </ul>
            </div> 
        </div>

    </div>



<script>
    function openForm() {
  document.getElementById("myForm").style.display = "block";
}

function closeForm() {
  document.getElementById("myForm").style.display = "none";
}
</script>

{% endblock content %}

user/templates/user/pages/dashboard_author.html
{% extends 'templates/pages/global.html' %}

{% block title %}Author register | {% endblock title %}
{% block content %}
    <div class="main-content center container gray-box" id='form-painting'>
        <h2>Cadastrar um pintor</h2>
        <div class="login-message">
            <h3><a href="{% url 'user:dashboard' %}">Dashboard</a></h3>
        </div>
        {% include 'templates/partials/messages.html' %}
        <div class="left">
            {% include 'templates/partials/form_author.html' %}
        </div>
    </div>


{% endblock content %}

user/templates/user/pages/dashboard_church.html
{% extends 'templates/pages/global.html' %}

{% block title %}Church register | {% endblock title %}
{% block content %}
    <div class="main-content center container gray-box" id="form-church">
        <h2>Cadastrar uma Igreja</h2>
        <div class="login-message">
            <h3><a href="{% url 'user:dashboard' %}">Dashboard</a></h3>
        </div>
        {% include 'templates/partials/messages.html' %}
        <div class="">
            {% include 'templates/partials/form_church.html' %}
        </div>
    </div>


{% endblock content %}

user/templates/user/pages/dashboard_engraving.html
{% extends 'templates/pages/global.html' %}

{% block title %}Registrar gravura | {% endblock title %}
{% block content %}
    <div class="main-content center container gray-box" id='form-painting'>
        <h2>Cadastrar uma Gravura</h2>
        <div class="login-message">
            <h3><a href="{% url 'user:dashboard' %}">Dashboard</a></h3>
        </div>
        {% include 'templates/partials/messages.html' %}
        <div class="left">
            {% include 'templates/partials/form_engraving.html' %}
        </div>
    </div>


{% endblock content %}

user/templates/user/pages/dashboard_painting.html
{% extends 'templates/pages/global.html' %}

{% block title %}Painting register | {% endblock title %}

{% block content %}
    <div class="main-content center container gray-box" id="form-painting">
        <h2>{{method}} uma pintura</h2>
        <div class="login-message">
            <h3 id="dashboard-option"><a class="dashboard-button" id="dashboard-back" href="{% url 'user:dashboard' %}">Dashboard</a></h3>
        </div>
        {% include 'templates/partials/messages.html' %}
        <div class="left">
            {% include 'templates/partials/form_painting.html' %}
        </div>
    </div>


{% endblock content %}

user/templates/user/pages/edit_user.html
{% extends 'templates/pages/global.html' %}

{% block title %}Login | {% endblock title %}
<div id="login-box">
{% block content %}
    <div class="center container gray-box" id="login-page">

        <h2>Editar perfil</h2>
        <br>
        {% include 'templates/partials/messages.html' %}
        {% include 'templates/partials/form.html' %}
        <div class="form-group">
            <a class="link-to-button" onclick="history.back()">Cancelar</a>
        </div>

    </div>
</div>
{% endblock content %}

user/templates/user/pages/login.html
{% extends 'templates/pages/global.html' %}

{% block title %}Login | {% endblock title %}
<div id="login-box">
{% block content %}
    <div class="center container gray-box" id="login-page">

        <h2>Login</h2>
        <br>
        <h4>Não possui conta? <a href="{% url 'user:register' %}">Clique aqui</a> para se registrar</h4>
        <br>
        {% include 'templates/partials/messages.html' %}
        {% include 'templates/partials/form.html' %}
    </div>
</div>
{% endblock content %}

user/templates/user/pages/paintings_published.html
{% extends 'templates/pages/global.html' %}

{% block title %}Pinturas publicadas | {% endblock title %}
{% block content %}
    {% include 'templates/partials/messages.html' %}
    <div class="login-message">
        <h2>Suas pinturas publicadas</h2>
        <h2>Obrigado {{usuario}} pela contribuição!</h2>
    </div>
    <div class="main-content main-content-list container">
        {% for painting in page.paintings %}          
            {% include 'museum/partials/painting.html' %} 
        {%empty%}  
        <h1>No paintings found here!</h1>
        {% endfor %}
    </div>
    <div class="container">
        {% include 'templates/partials/pagination.html' %}
    </div>

{% endblock content %}

user/templates/user/pages/register.html
{% extends 'templates/pages/global.html' %}

{% block title %}Register | {% endblock title %}
{% block content %}
    <div class="center container gray-box" id="reg-page">
        <h2>Registro</h2>
        <br>
        <h4>Já possui conta? <a href="{% url 'user:login' %}">Clique aqui</a> para realizar o login</h4>
        <br>
        {% include 'templates/partials/messages.html' %}
        {% include 'templates/partials/form.html' %}
    </div>
{% endblock content %}