museum/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from museum import views

app_name = 'painting'

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.search, name='search'),
    path('church/all/', views.churches, name='church_all'),
    path('painter/all/', views.painters, name='painter_all'),
    path('engraving/all/', views.engravings, name='engraving_all'),
    path("paintings/tag/<slug:slug>/", views.tags_paintings, name="tag"),
    path('painting/<int:painting_id>/', views.detail_painting, name='detail'),
    path('church/<int:id_church>/', views.detail_church, name='church'),
    path('painter/<int:id_painter>/', views.detail_painter, name='painter'),
    path('engraving/<int:id_engraving>/', views.detail_engraving, name='engraving'),
    path('user/dashboard/painting/<int:painting_id>/', views.detail_painting_not_published, name='detail_not_published'),
    path('info/', views.info, name='info'),
]

urlpatterns += staticfiles_urlpatterns()

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('museum.urls')),
    path('user/', include('user.urls')),
    path('__debug__/', include('debug_toolbar.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('register/create/', views.register_create, name='register_create'),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout/', views.logout_user, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('edit/', views.edit_user, name='edit'),
    path('painting/create/', views.painting_create, name='painting_create'),
    path('painting/published/', views.painting_user_published, name='paintings_published'),
    path('author/create/', views.painting_author_create, name='painting_author_create'),
    path('church/create/', views.painting_church_create, name='painting_church_create'),
    path('engraving/all/', views.engravings, name= 'painting_engraving_all'),
    path('engraving/create/', views.engraving_create, name='painting_engraving_create'),
    path('engraving/create/data/', views.engraving_create_data, name='engraving_create_data'),
    path('painting/<int:id>/delete/', views.painting_delete, name='painting_delete'),
    path('painting/<int:id>/edit/', views.painting_edit, name='painting_edit'),
]

website/templates/partials/footer.html
<footer class="main-footer">
    <div class="developer">
      <a href="https://github.com/GuilhermeGonSoares" target="_blank" rel="noreferrer noopener">
        <i class="fas fa-code-branch"></i>  
        Guilherme</a>
      <a href="https://github.com/yantavares" target="_blank" rel="noreferrer noopener">
        <i class="fas fa-code-branch"></i>  
         Yan</a>
    </div>
  
    <div class="powered">
      <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
  </footer>

website/templates/partials/form.html
<form action="{% url form_action %}" method="POST">
    {% csrf_token %}
    <div class="form-content form-content-grid">
        {% for field in form %}
            <div class="form-group {{field.field.widget.attrs.class}}">
                <label for="{{field.id_for_label}}">{{field.label}}</label>
                {{field}}

                {% if field.help_text %}
                    <p class="help-text">{{field.help_text}}</p>
                {% endif %}

                {{field.errors}}
            </div>

        {% endfor %}
    </div>

    {% if form.errors %}
        <div class="form-content form-content-grid">
            <div class="form-group">
                <div class="message message-error">
                    Por favor corrija os erros no formulário
                </div>
            </div>
        </div>
    {% endif %}

    <div class="form-content form-content-grid">
        <div class="form-group">
            <button class="plaintext-button" type="submit">Enviar</button>
        </div>
    </div>

</form>

website/templates/partials/form_author.html
<form class="form_author_create" action="{% url 'user:painting_author_create' %}" method="POST">
    {% csrf_token %}
    
    {% if form.errors %}
    <div class="form-content form-content-grid">
        <div class="form-group">
            <div class="message message-error">
                Por favor corrijas os erros no formulário
            </div>
        </div>
    </div>
    {% endif %}
    
    <div class="form-content form-content-grid">
        {% for field in form %}
        <div class="form-group {{field.field.widget.attrs.class}}">
            <label for="{{field.id_for_label}}">{{field.label}}</label>
            {{field}}

            {% if field.help_text %}
            <p class="help-text">{{field.help_text}}</p>
            {% endif %}

            {{field.errors}}
        </div>

        {% endfor %}
    </div>

    

    <div class="form-content form-content-grid">
        <div class="form-group">
            <a class="link-to-button" onclick="history.back()">Cancelar</a>
            <button id="confirm-author-create" class="plaintext-button" type="submit">Enviar</button>
        </div>
    </div>

</form>

website/templates/partials/form_church.html
<form action="{% url 'user:painting_church_create' %}" method="POST">
    {% csrf_token %}
    {% if form.errors %}
        <div class="form-content form-content-grid">
            <div class="form-group">
                <div class="message message-error">
                    Por favor corrija os erros no formulário
                </div>
            </div>
        </div>
    {% endif %}
    
    <div class="form-content form-content-church">
        {% for field in form %}
            <div class="form-group {{field.field.widget.attrs.class}}">
                <label for="{{field.id_for_label}}">{{field.label}}</label>
                <input type="hidden" id="cities" name="variable" value="{{cities}}">
                {{field}}
                
                {% if field.help_text %}
                    <p class="help-text">{{field.help_text}}</p>
                {% endif %}
                
                {{field.errors}}
            </div>

        {% endfor %}
    </div>

    

    <div class="form-content form-content-grid">
        <div class="form-group">
            <a class="link-to-button" onclick="history.back()">Cancelar</a>
          <button class="plaintext-button" type="submit">Enviar</button>
        </div>
    </div>
</form>

website/templates/partials/form_engraving.html
<script>
    $(document).ready(function(){
        $('#ddlselect').select2({
            placeholder:'Selecione o pintor',
            closeOnSelect:false,
        });
        $('#ddlselect').on('change', function(){
            var display = $('#ddlselect').val();
            $('#authors_selected').val(display);
        });
    });
</script>

<form class="form_author_create" action="{% url 'user:painting_engraving_create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-content form-content-grid">
        {% for field in form %}
        <div class="form-group {{field.field.widget.attrs.class}}">
            <label for="{{field.id_for_label}}">{{field.label}}</label>
            {% if field.name == 'author' %}
                <p class="church-select">Não achou o pintor na lista?
                <a id="create_author" href="{% url 'user:painting_author_create' %} ">Adicione</a></p> 
                
                <select name="pintores_selecionados" id="ddlselect" multiple>
                    {% for author in authors %}
                        <option value="{{author.id}}">{{author.name}}</option>
                    {% endfor %}
                </select>
            {% else %}
                {{field}}
            {% endif %}

            {% if field.help_text %}
            <p class="help-text">{{field.help_text}}</p>
            {% endif %}

            {{field.errors}}
        </div>
        {% if field.name == 'cover' and field.value.url %}
        <div class="span-2">
            <img src="{{field.value.url}}" alt="Capa para {{painting.name}}">
        </div>
        {% endif %}
        {% endfor %}
    </div>

    {% if form.errors %}
    <div class="form-content form-content-grid">
        <div class="form-group">
            <div class="message message-error">
                Por favor corrijas os erros no formulário
            </div>
        </div>
    </div>
    {% endif %}

    <div class="form-content form-content-grid">
        <div class="form-group">
            <a class="link-to-button" onclick="history.back()">Cancelar</a>
            <button id="confirm-author-create" class="plaintext-button" type="submit">Enviar</button>
        </div>
    </div>

</form>

website/templates/partials/form_painting.html
<script>
    $(document).ready(function(){
        $('#ddlselect').select2({
            placeholder:'Selecione o pintor',
            closeOnSelect:false,
        });
        if (sessionStorage.getItem("authors") !== null){
            const authors_selected = sessionStorage.getItem("authors").split(',');
            console.log(authors_selected);
            $('#ddlselect').val(authors_selected).change();
        }

    });
    
</script>

<form class="create_painting" action="{{form_action}}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% if form.errors %}
        <div class="form-content form-content-grid">
            <div class="form-group">
                <div class="message message-error">
                    Por favor corrija os erros no formulário
                </div>
            </div>
        </div>
    {% endif %}
    <div class="form-content form-content-grid">
        {% for field in form %}
        <div class="form-group {{field.field.widget.attrs.class}}">
            <label for="{{field.id_for_label}}">{{field.label}}</label>

            {% if field.name == 'author' %}
                <p class="church-select">Não achou o pintor na lista?
                <a id="create_author" href="{% url 'user:painting_author_create' %} ">Adicione</a></p> 
                
                <select name="pintores_selecionados" id="ddlselect" multiple>
                    {% for author in authors %}
                    {% if author in authors_registered %}
                        <option selected="selected" value="{{author.id}}">{{author.name}}</option>
                    {% else %}
                        <option value="{{author.id}}">{{author.name}}</option>
                    {% endif %}
                    {% endfor %}
                </select>
                <input type="hidden" id="myVar" name="variable" value="{{ authors_json }}">
                
    
            {% elif field.name == 'church' %}
                <p class="church-select">Não achou a igreja na lista?
                <a id="create_church" href="{% url 'user:painting_church_create' %} ">Adicione</a></p>
                {{field}}
            {% elif field.name == 'engraving' %}          
                    <p>A sua obra possui gravuras relacionadas a ela? <a id="create_engraving" href="{% url 'user:painting_engraving_all' %}">Clique aqui</a> para adicioná-las ou editá-las.</p>
                
                    <div class="painting-gravuras">
                    {% if engravings %}
                        <p style="text-decoration:underline; color:black;">Gravuras selecionadas:</p>
                    {% else %}
                        <p style="text-decoration:underline; color:black;" >Nenhuma gravura selecionada!</p>
                    {% endif %}
                        <ul>
                            {% for engraving in engravings %}
                                <li>{{engraving.name}}</li>
                            {% endfor %}
                        </ul>
                    </div>
                
            {% else %}
                {{field}}
            {% endif %}


            {% if field.help_text %}
            <p class="help-text">{{field.help_text}}</p>
            {% endif %}

            {{field.errors}}
        </div>



        {% if field.name == 'cover' and field.value.url %}
        <div class="span-2">
            <img src="{{field.value.url}}" alt="Capa para {{painting.name}}">
        </div>
        {% endif %}
        {% endfor %}
    </div>

    <div class="form-content form-content-grid">
        <div class="form-group">
            <a class="link-to-button" onclick="confirmCancel()">Cancelar</a>
            <button class="plaintext-button" type="submit">Enviar</button>
        </div>
    </div>

</form>

website/templates/partials/head.html
{% load static %}
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/fontawesome.min.css"
    integrity="sha512-P9vJUXK+LyvAzj8otTOKzdfF1F3UYVl13+F8Fof8/2QNb8Twd6Vb+VD52I7+87tex9UXxnzPgWA3rH96RExA7A=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/brands.min.css"
    integrity="sha512-sVSECYdnRMezwuq5uAjKQJEcu2wybeAPjU4VJQ9pCRcCY4pIpIw4YMHIOQ0CypfwHRvdSPbH++dA3O4Hihm/LQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/solid.min.css"
    integrity="sha512-tk4nGrLxft4l30r9ETuejLU0a3d7LwMzj0eXjzc16JQj+5U1IeVoCuGLObRDc3+eQMUcEQY1RIDPGvuA7SNQ2w=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

<link rel="stylesheet" href="{% static 'static/css/style.css' %}">

<script src="https://kit.fontawesome.com/71fc09f195.js" crossorigin="anonymous"></script>
<!--<link rel="stylesheet" href="{% static 'global/css/global-style.css' %}">-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js" integrity="sha512-2ImtlRlf2VVmiGZsjm9bEyhjGW4dU7B6TNwh/hx/iSByxNENtj3WVE6o/9Lj4TJeVXPi4bnOIMXFIJJAeufa0A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" integrity="sha512-nMNlpuaDPrqlEls3IX/Q56H36qvBASwb3ipuo3MxeWbsQB1881ox0cRv7UPTgBlriqoynt35KjEwgGUeUXIPnw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

website/templates/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url 'painting:home' %}">
                <i class="fas fa-palette main-logo-icon"></i>
                <span>RafArte</span>
            </a>
        </h1>
    </div>

    <div class="navbar">

        <div class="navbar-item">
            <a href="{% url 'painting:home' %}"><i class="fas fa-house"></i> Home</a>
        </div>
        {% if user.is_authenticated %}
        <div class="navbar-item">
            <a href="{% url 'user:dashboard' %}"><i class="fas fa-book-open"></i> DashBoard</a>
        </div>
        <div class="navbar-item">
            <form action="{% url 'user:logout' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="username" value="{{request.user.username}}">
                
                <button class="plaintext-button" type="submit"><i class="fas fa-right-from-bracket"></i> Deslogar</button>
            </form>
        </div>
    {% endif %}
    {% if not user.is_authenticated %}
        <div class="navbar-item">
            
            <a href="{% url 'user:login' %}"><i class="fas fa-user"></i> Logar</a>
        </div>
        <div class="navbar-item">
            <a href="{% url 'user:register' %}"> <i class="fa-solid fa-face-smile"></i> Registrar</a>
        </div>
        
    {% endif %}
    </div>
    
</header>

website/templates/partials/messages.html
{% if messages %}
    <div class="center container messages-container">
        {% for message in messages %}
            <div class="message {{message.tags}}">
                {{message}}
            </div>
        {% endfor %}
    </div>
{% endif %}

website/templates/partials/pagination.html
<div class="container pagination center-flex">
    <div class="pagination-content">
        {% if is_search is True %}
            {% for numeration in page.pagination %}
                {% if numeration == '…' %}
                    {{numeration}}
                {% elif page.current_page == numeration %}
                    <a class="page-link page-item page-current" href="?filter={{filter}}&q={{search_result}}&page={{numeration}}"> {{numeration}}</a>
                {% else %}
                    <a class="page-link page-item" href="?filter={{filter}}&q={{search_result}}&page={{numeration}}"> {{numeration}}</a>
                {% endif %}
            {% endfor %}
        {% else %}
            {% for numeration in page.pagination %}
                {% if numeration == '…' %}
                    {{numeration}} 
                {% elif page.current_page == numeration %}
                    <a class="page-link page-item page-current" href="?page={{numeration}}"> {{numeration}}</a>
                {% else %}
                    <a class="page-link page-item" href="?page={{numeration}}"> {{numeration}}</a>
                {% endif %}
            {% endfor %}
        {% endif %}
        
    
    </div>
</div>

website/templates/partials/search.html
<div class="search-container">
    <div class="container">
        <div class="center" id="see-all">
            <a class="dashboard-button-dark{{sobre}}" href="{% url 'painting:info' %}"> Sobre </a>
            <a class="dashboard-button-dark{{obras}}" href="{% url 'painting:home' %}"> Obras </a>
            <a class="dashboard-button-dark{{igrejas}}" href="{% url 'painting:church_all' %}"> Igrejas </a>
            <a class="dashboard-button-dark{{pintores}}" href="{% url 'painting:painter_all' %}"> Pintores </a>
            <a class="dashboard-button-dark{{gravuras}}" href="{% url 'painting:engraving_all' %}"> Gravuras </a>
        </div>

        {% if searchbar is not False %}
        {% include 'templates/partials/searchbar.html' %}
        {% endif %}


    </div>

</div>

website/templates/partials/searchbar.html
<form action="{% if search_action %}{% url search_action %}{% endif %} " method="GET" class="search-form">
    <select hidden name="filter" required id="filter">
        <option {{ filterPainting }} value="paintings">Obras</option>
        <option {{ filterChurch }} value="churches">Igrejas</option>
        <option {{ filterPainter }} value="painters">Pintores</option>
        <option {{ filterEngraving }} value="engravings">Gravuras</option>
    </select>
    <input placeholder="{{placeholder}}" type="search" class="search-input" name="q" value="" required>
    <button type="submit" class="search-button"><i class="fas fa-search"></i></button>
</form>